"""Remove ticket column from users table and added full_name_from_tg column

Revision ID: 3cce5895ad6a
Revises: 98744efccd80
Create Date: 2024-11-24 18:59:26.903762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cce5895ad6a'
down_revision: Union[str, None] = '98744efccd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name_from_tg', sa.String(), nullable=True))
    op.drop_column('users', 'ticket')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ticket', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'full_name_from_tg')
    # ### end Alembic commands ###
