"""Add is_active column to Lottery

Revision ID: c4a61144b3cf
Revises: 21e6ac2dbcd1
Create Date: 2025-02-13 14:33:21.669663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4a61144b3cf'
down_revision: Union[str, None] = '21e6ac2dbcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # op.drop_column('users', 'date_joined')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('lotteries', 'is_active')
    # ### end Alembic commands ###
