"""update migrations. added relationship with other tables

Revision ID: d52c2268a6a4
Revises: 3b8a909bef56
Create Date: 2024-11-25 11:38:10.855844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52c2268a6a4'
down_revision: Union[str, None] = '3b8a909bef56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
